"""Builds the visit care-summary PDF, on demand, for one specific viewer.

SECURITY CHANGE (was: upload to Cloudinary and hand back `secure_url`).
The old flow uploaded every generated care summary — vitals, patient name,
and for the nurse copy her internal clinical notes — to a *public* Cloudinary
URL in the `visit-reports/` folder. Anyone holding that link (forwarded
WhatsApp message, browser history, proxy logs, a screenshot of the address
bar) could download the PDF with no login at all, forever. That made any
watermark pointless: no screenshot is needed when the file itself is public.

Now the PDF is rendered in memory and streamed back only through an
authenticated, audited, one-time download (see visits.py). Nothing is
persisted anywhere. PDFs generated by the old flow are still sitting in
Cloudinary and must be deleted (see scripts/purge_public_visit_reports.py).

This module still never decides *who* may see which view — the API layer
has already established that and passes `include_clinical_notes`.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.company import get_company
from app.models.enums import UserRole
from app.models.models import Patient, User, VisitRecord, VitalSignReading, WorkerProfile
from app.services.visit_report_pdf import PdfWatermark, render_visit_report_pdf

logger = logging.getLogger(__name__)

_ROLE_LABELS = {
    UserRole.worker: "Care Professional",
    UserRole.consumer: "Family / Patient",
    UserRole.admin: "Admin",
}


def role_label(role: UserRole) -> str:
    return _ROLE_LABELS.get(role, role.value.replace("_", " ").title())


def mask_phone(phone: Optional[str]) -> Optional[str]:
    """'+919876543210' -> '******3210' (enough to identify, not to dial)."""
    if not phone:
        return None
    digits = "".join(ch for ch in phone if ch.isdigit())
    if len(digits) < 4:
        return None
    return "******" + digits[-4:]


def watermark_identity(user: User) -> tuple[str, Optional[str]]:
    """(display name, hint) for a watermark — never empty.

    `full_name` is optional on User (OTP sign-ups have none), so fall back to
    the email, then a short user id; the masked phone is always added as a
    second identifier so two "Ravi Kumar"s can be told apart.
    """
    name = (user.full_name or "").strip()
    if not name:
        name = (user.email or "").strip() or f"User {str(user.id)[:8]}"
    return name, mask_phone(user.phone_e164)


async def latest_vitals(db: AsyncSession, booking_id: UUID) -> Optional[dict]:
    res = await db.execute(
        select(VitalSignReading)
        .where(VitalSignReading.booking_id == booking_id)
        .order_by(VitalSignReading.recorded_at.desc())
        .limit(1)
    )
    v = res.scalar_one_or_none()
    if v is None:
        return None
    return {
        "bp_systolic": v.bp_systolic,
        "bp_diastolic": v.bp_diastolic,
        "pulse": v.pulse,
        "spo2": v.spo2,
        "temperature_f": float(v.temperature_f) if v.temperature_f is not None else None,
        "recorded_at": v.recorded_at.isoformat() if v.recorded_at else None,
    }


@dataclass(frozen=True)
class VisitReportPdfInputs:
    """Everything the renderer needs, loaded up-front (async DB work) so the
    CPU-bound reportlab render can then run in a worker thread."""

    booking_ref: str
    patient_name: str
    nurse_name: str
    nurse_council_no: Optional[str]
    check_in_at: Optional[datetime]
    check_out_at: Optional[datetime]
    duration_minutes: Optional[int]
    vitals: Optional[dict]
    family_summary: Optional[str]
    care_notes: Optional[str]
    include_clinical_notes: bool


async def load_visit_report_pdf_inputs(
    db: AsyncSession,
    visit: VisitRecord,
    booking_ref: str,
    *,
    include_clinical_notes: bool,
) -> VisitReportPdfInputs:
    pres = await db.execute(select(Patient).where(Patient.id == visit.patient_id))
    patient = pres.scalar_one_or_none()

    wres = await db.execute(select(WorkerProfile).where(WorkerProfile.id == visit.worker_id))
    worker = wres.scalar_one_or_none()
    nurse_name = "\u2014"
    if worker is not None:
        ures = await db.execute(select(User).where(User.id == worker.user_id))
        nurse_user = ures.scalar_one_or_none()
        nurse_name = (nurse_user.full_name if nurse_user and nurse_user.full_name else None) or "\u2014"

    return VisitReportPdfInputs(
        booking_ref=booking_ref,
        patient_name=(patient.full_name if patient and patient.full_name else "\u2014"),
        nurse_name=nurse_name,
        nurse_council_no=(worker.registration_no if worker else None),
        check_in_at=visit.check_in_at,
        check_out_at=visit.check_out_at,
        duration_minutes=visit.actual_duration_minutes,
        vitals=await latest_vitals(db, visit.booking_id),
        family_summary=visit.family_summary,
        # Never even loaded into the family view's inputs.
        care_notes=visit.care_notes if include_clinical_notes else None,
        include_clinical_notes=include_clinical_notes,
    )


def render_visit_report(inputs: VisitReportPdfInputs, watermark: PdfWatermark) -> bytes:
    """Synchronous render — call via run_in_threadpool from async code."""
    return render_visit_report_pdf(
        company=get_company(),
        booking_ref=inputs.booking_ref,
        patient_name=inputs.patient_name,
        nurse_name=inputs.nurse_name,
        nurse_council_no=inputs.nurse_council_no,
        check_in_at=inputs.check_in_at,
        check_out_at=inputs.check_out_at,
        duration_minutes=inputs.duration_minutes,
        vitals=inputs.vitals,
        summary_text=inputs.family_summary,
        summary_label="Summary for the family",
        include_clinical_notes=inputs.include_clinical_notes,
        care_notes=inputs.care_notes if inputs.include_clinical_notes else None,
        watermark=watermark,
        generated_at=watermark.generated_at,
    )
