#!/usr/bin/env python3
"""Build the UAT `.env` (in the UAT folder) from the old EC2 `.env`.

Copies the old file, then OVERRIDES everything that could touch production:
database, Redis, JWT secret, Razorpay (test keys), payouts, WhatsApp, e-Sign.
Prints key NAMES only, never values.

    cd ~/nurseconnect-uat
    python3 deploy/uat/make_uat_env.py --host staging-api.nurseconnect.co.in
"""
import argparse
import os
import secrets
import stat
import sys
from urllib.parse import urlsplit, urlunsplit

SRC = os.path.expanduser("~/nurseconnect--backend/.env")
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DST = os.path.join(ROOT, ".env")
FILL = "__FILL_ME__"


def read_env(path):
    out = {}
    for line in open(path, encoding="utf-8"):
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def with_path(url, path):
    p = urlsplit(url)
    return urlunsplit((p.scheme, p.netloc, path, p.query, p.fragment))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", required=True, help="UAT API hostname, e.g. staging-api.nurseconnect.co.in")
    ap.add_argument("--db", default="nurseconnect_uat")
    ap.add_argument("--force", action="store_true", help="overwrite an existing UAT .env")
    a = ap.parse_args()

    if os.path.exists(DST) and not a.force:
        sys.exit(f"{DST} already exists. Re-run with --force to overwrite it.")
    if not os.path.exists(SRC):
        sys.exit(f"Cannot find {SRC}")

    env = read_env(SRC)
    changed = []

    def put(k, v):
        env[k] = v
        changed.append(k)

    def drop_prefix(prefix):
        for k in [k for k in env if k.startswith(prefix)]:
            del env[k]
            changed.append(f"{k} (removed)")

    put("APP_ENV", "staging")
    put("APP_DEBUG", "false")
    put("MOCK_EXTERNAL_PROVIDERS", "false")
    for k in ("OTP_DEV_MODE", "EMAIL_DEV_MODE", "OTP_DEV_FIXED_CODE"):
        if k in env:
            del env[k]
            changed.append(f"{k} (removed)")

    for k in ("DATABASE_URL", "DATABASE_URL_SYNC"):
        put(k, with_path(env[k], "/" + a.db))
    put("REDIS_URL", with_path(env["REDIS_URL"], "/10"))
    put("CELERY_BROKER_URL", with_path(env["CELERY_BROKER_URL"], "/11"))
    put("CELERY_RESULT_BACKEND", with_path(env["CELERY_RESULT_BACKEND"], "/12"))

    put("JWT_SECRET_KEY", secrets.token_hex(32))
    put("RAZORPAY_KEY_ID", FILL)
    put("RAZORPAY_KEY_SECRET", FILL)
    put("RAZORPAY_WEBHOOK_SECRET", secrets.token_hex(16))
    drop_prefix("RAZORPAYX_")   # payouts must never run from UAT
    drop_prefix("DIGIO_")
    drop_prefix("INTERAKT_")

    for k in ("MSG91_AUTH_KEY", "MSG91_TEMPLATE_ID", "RESEND_API_KEY", "EMAIL_FROM_ADDRESS"):
        if not env.get(k):
            put(k, FILL)

    put("PUBLIC_API_URL", f"https://{a.host}")
    put("CORS_ORIGINS", f"https://{a.host}")
    put("CONTRACT_STAGE2_ENABLED", "false")
    put("RUN_SEED_ON_STARTUP", "false")

    with open(DST, "w", encoding="utf-8") as f:
        f.write("# UAT environment - generated by deploy/uat/make_uat_env.py. Never commit.\n")
        for k, v in env.items():
            f.write(f"{k}={v}\n")
    os.chmod(DST, stat.S_IRUSR | stat.S_IWUSR)

    print(f"Wrote {DST} (mode 600)\n")
    print("Overridden / removed (names only):")
    for k in changed:
        print("  -", k)
    print("\nYou must fill these by hand (nano .env):")
    for k, v in env.items():
        if v == FILL:
            print("  *", k)
    print("\nCopied unchanged from the old file - review: ")
    for k in sorted(env):
        if k.startswith(("CLOUDINARY_", "FIREBASE_", "APNS_", "REALTIMEKIT_", "SMTP_")):
            print("  ?", k)
    print("\nNext: python3 deploy/uat/preflight.py")


if __name__ == "__main__":
    main()
